"use strict"

module.exports = {
    
    INITIALIZE_CONDOMINIO : "INITIALIZE_CONDOMINIO",
    CREATE_CONDOMINIO: "CREATE_CONDOMINIO",
    UPDATE_CONDOMINIO: "UPDATE_CONDOMINIO",
    DELETE_CONDOMINIO: "DELETE_CONDOMINIO",
    SAVE_STATE_CONDOMINIO: "SAVE_STATE_CONDOMINIO",
    GET_STATE_CONDOMINIO: "GET_STATE_CONDOMINIO",
    CREATE_ENDERECO: "CREATE_ENDERECO",
    CLEAN_ENDERECO: "CLEAN_ENDERECO",
    INIT_ENDERECO: "INIT_ENDERECO",
    UPDATE_ENDERECO: "UPDATE_ENDERECO",
    DELETE_ENDERECO: "DELETE_ENDERECO",
    CREATE_FACILITY: "CREATE_FACILITY",
    CLEAN_FACILITY: "CLEAN_FACILITY",
    INIT_FACILITY: "INIT_FACILITY",
    UPDATE_FACILITY: "UPDATE_FACILITY",
    DELETE_FACILITY: "DELETE_FACILITY",
    DELETE_CONDOMINIO_ENDERECO: "DELETE_CONDOMINIO_ENDERECO",
    BUSCA_ENDERECO: "BUSCA_ENDERECO"

};